DROP TABLE voting IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE user_role IF EXISTS;
DROP TABLE restaurant IF EXISTS;
DROP TABLE menu IF EXISTS;
DROP TABLE restaurant_menu IF EXISTS;
DROP TABLE dish IF EXISTS;
DROP TABLE dish_menu IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS INTEGER
    START WITH 100000;

CREATE TABLE users
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(16)  NOT NULL
);

CREATE TABLE user_role
(
    user_id         INTEGER,
    role            VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE restaurant
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name            VARCHAR(255) NOT NULL
);

CREATE TABLE menu
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    restaurant_id   INTEGER NOT NULL,
    date            DATE DEFAULT CURRENT_DATE NOT NULL
);

CREATE TABLE restaurant_menu
(
    restaurant_id   INTEGER NOT NULL FOREIGN KEY REFERENCES restaurant (id),
    menu_id         INTEGER NOT NULL FOREIGN KEY REFERENCES menu (id),
    PRIMARY KEY (restaurant_id, menu_id)
);

CREATE TABLE dish
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    price           DECIMAL NOT NULL,
    menu_id         INTEGER NOT NULL,
    FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE
);

CREATE TABLE dish_menu
(
    dish_id INTEGER NOT NULL FOREIGN KEY REFERENCES dish (id),
    menu_id INTEGER NOT NULL FOREIGN KEY REFERENCES menu (id),
    PRIMARY KEY (dish_id, menu_id)
);

CREATE TABLE voting
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    user_id         INTEGER,
    menu_id         INTEGER,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE
)